In [15]:
import pandas as pd


## list
lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks']

df = pd.DataFrame(lst)
print(df)

print("#"*50)
## dictionary ( dict of narray/list)
data = {
    'Name': ['Tom','Nick','Kris','Jack'],
    'Age':[20, 21, 19, 18]
}

df = pd.DataFrame(data)
print(df)


print("#"*50)
## column selection
data = {
        'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']
       }

df = pd.DataFrame(data)
#print(df['Name'])                    ## select 1 column
print(df[['Name','Qualification']])  ## select 2 columns

        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks
##################################################
   Name  Age
0   Tom   20
1  Nick   21
2  Kris   19
3  Jack   18
##################################################
     Name Qualification
0     Jai           Msc
1  Princi            MA
2  Gaurav           MCA
3    Anuj           Phd

In [33]:
## row selection
data = pd.read_csv("nba.csv", index_col = 'Name')
# first = data.loc["Avery Bradley"]
# second = data.loc["R.J. Hunter"]
# print(first, "\n\n\n", second)


first = data["Age"]
print(first)

## 讀出 column
# data = pd.read_csv("nba.csv")
# df = pd.DataFrame(data)
# print(df.columns)

Name
Avery Bradley              25.0
Jae Crowder                25.0
John Holland               27.0
R.J. Hunter                22.0
Jonas Jerebko              29.0
Amir Johnson               29.0
Jordan Mickey              21.0
Kelly Olynyk               25.0
Terry Rozier               22.0
Marcus Smart               22.0
Jared Sullinger            24.0
Isaiah Thomas              27.0
Evan Turner                27.0
James Young                20.0
Tyler Zeller               26.0
Bojan Bogdanovic           27.0
Markel Brown               24.0
Wayne Ellington            28.0
Rondae Hollis-Jefferson    21.0
Jarrett Jack               32.0
Sergey Karasev             22.0
Sean Kilpatrick            26.0
Shane Larkin               23.0
Brook Lopez                28.0
Chris McCullough           21.0
Willie Reed                26.0
Thomas Robinson            25.0
Henry Sims                 26.0
Donald Sloan               28.0
Thaddeus Young             27.0
                           ...
Al-Farouq Aminu            25.0
Pat Connaughton            23.0
Allen Crabbe               24.0
Ed Davis                   27.0
Maurice Harkless           23.0
Gerald Henderson           28.0
Chris Kaman                34.0
Meyers Leonard             24.0
Damian Lillard             25.0
C.J. McCollum              24.0
Luis Montero               23.0
Mason Plumlee              26.0
Brian Roberts              30.0
Noah Vonleh                20.0
Trevor Booker              28.0
Trey Burke                 23.0
Alec Burks                 24.0
Dante Exum                 20.0
Derrick Favors             24.0
Rudy Gobert                23.0
Gordon Hayward             26.0
Rodney Hood                23.0
Joe Ingles                 28.0
Chris Johnson              26.0
Trey Lyles                 20.0
Shelvin Mack               26.0
Raul Neto                  24.0
Tibor Pleiss               26.0
Jeff Withey                26.0
NaN                         NaN
Name: Age, Length: 458, dtype: float64