### https://oranwind.org/python-pandas-ji-chu-jiao-xue/
## git config core.autocrlf true
#
#  git add .
# warning: LF will be replaced by CRLF in .ipynb_checkpoints/DF_20190529_markdown-checkpoint.ipynb.
# The file will have its original line endings in your working directory
# warning: LF will be replaced by CRLF in DF_20190529_markdown.ipynb.
# The file will have its original line endings in your working directory

In [5]:
# pandas Series:
# select = pd.Series(data, index = idx)


import pandas as pd

cars = ["BMW", "BENZ", "Toyota","Nissan", "Lexus"]
print(cars)
print(type(cars))

print("#"*50)

select = pd.Series(cars)
print(select)
print(type(select))

['BMW', 'BENZ', 'Toyota', 'Nissan', 'Lexus']
<class 'list'>
##################################################
0       BMW
1      BENZ
2    Toyota
3    Nissan
4     Lexus
dtype: object
<class 'pandas.core.series.Series'>

import pandas as pd

dicts = {
    "factory":"Taipei",
    "sensor1":"1",
    "sensor2":"2",
    "sensor3":"3",
    "sensor4":"4",
    "sensor5":"5",
}

select = pd.Series(dicts, index = dicts.keys())
print(select)
print("#"*50)

## 索引值取值
print(select[0])
print("#"*50)

## 索引值取值
print(select[[0,2,5]])
print("#"*50)

## Key值取值
print(select[['factory','sensor1','sensor3']])
print("#"*50)


## 資料切片, 取到index 2之前（ 0-1）
print(select[:2])
print("#"*50)

## 資料切片, 取Key值=sensor2 之後所有的值
print(select["sensor2":])

In [16]:
singleCar = 'BENZ'
select = pd.Series(singleCar)
print(select)
select = pd.Series(singleCar, index = range(3))
print(select)

0    BENZ
dtype: object
0    BENZ
1    BENZ
2    BENZ
dtype: object

In [22]:
###### DataFrame

import pandas as pd


## Dictionary

groups = ['Movies','Sports','Coding','Fishing','Dancing','Cooking']
num = [46, 8, 12, 12, 6, 58]

dicts = {
    
    "groups": groups,
    "num": num
}

select_df = pd.DataFrame(dicts)
print(select_df)
print("#"*50)

## List

#arr = groups2 =[ ["Movies", 46], ["Sports",8], ["Coding",12], ["Fishing",12], ["Dancing",6], ["Cooking",8] ]
arr = groups2 =[ ["Movies", 46, "John"], ["Sports",8, "Acer"], ["Coding",12, "kk"], ["Fishing",12,"Miro"], ["Dancing",6,"Danny"], ["Cooking",8,"Jill"] ]
# print(groups2)
# print(type(groups2))
# print(arr)
# print(type(arr))

#df = pd.DataFrame(arr)     ##標題列為 0 1
#print(df.columns)   # RangeIndex(start=0, stop=3, step=1)

#df = pd.DataFrame(groups2) ##標題列為 0 1
#print(df.columns)    # RangeIndex(start=0, stop=3, step=1)

df = pd.DataFrame(arr, columns = ["name","num","who"])   ##修改標題列, 需對稱 List中的欄位
print(df.columns)   # Index(['name', 'num', 'who'], dtype='object')
print(df)

    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  Cooking   58
##################################################
Index(['name', 'num', 'who'], dtype='object')
      name  num    who
0   Movies   46   John
1   Sports    8   Acer
2   Coding   12     kk
3  Fishing   12   Miro
4  Dancing    6  Danny
5  Cooking    8   Jill

In [24]:
## DataFrame 操作

groups = ['Movies','Sports','Coding','Fishing','Dancing','Cooking']
num = [46, 8, 12, 12, 6, 58]

dicts = {
    
    "groups": groups,
    "num": num
}

select_df = pd.DataFrame(dicts)
print(select_df)
print("="*50)

## 回傳列數與欄數
print(select_df.shape)
print("="*50)

## 回傳描述性統計
print(select_df.describe())
print("="*50)

## 回傳前 n 筆
print(select_df.head(3))
print("="*50)

## 回傳最後 n筆
print(select_df.tail(3))
print("="*50)

## 回傳欄位名稱
print(select_df.columns)
print("="*50)

## 回傳 index
print(select_df.index)
print("="*50)

## 回傳資料內容
print(select_df.info)
print("="*50)

    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  Cooking   58
==================================================
(6, 2)
==================================================
             num
count   6.000000
mean   23.666667
std    22.393451
min     6.000000
25%     9.000000
50%    12.000000
75%    37.500000
max    58.000000
==================================================
   groups  num
0  Movies   46
1  Sports    8
2  Coding   12
==================================================
    groups  num
3  Fishing   12
4  Dancing    6
5  Cooking   58
==================================================
Index(['groups', 'num'], dtype='object')
==================================================
RangeIndex(start=0, stop=6, step=1)
==================================================
<bound method DataFrame.info of     groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  Cooking   58>

In [46]:
## DataFrame 資料選擇與篩選

groups = ['Movies','Sports','Coding','Fishing','Dancing','Cooking']
num = [46, 8, 12, 12, 6, 58]

dicts = {
    "groups":groups,
    "num":num
}


select_df2 = pd.DataFrame(dicts)
print(select_df2)
print("="*50)

## 取第一列第二欄 的值
print(select_df2.iloc[0,1])
print("="*50)

## 取第一列 的組名與人數
print(select_df2.iloc[0:1,:])
## 取第二列 的組名與人數
print(select_df2.iloc[1:2,:])
## 取第四列 的組名與人數
print(select_df2.iloc[3:4,:])
#print(select_df2.iloc[3:5,:])  #取了3,4筆
print("="*50)

## 取各組人數， 第二欄
print(select_df2.iloc[:,1])
## 取各組人數， 第一欄
#print(select_df2.iloc[:,0])
print("="*50)


## 取各組人數，指定Key值
print(select_df2["num"])
print("="*50)

## 取各組人數，指定num 欄位
print(select_df2.num)
print("="*50)

## 布林值篩選
#out_df = select_df2
out_df = select_df2[select_df2.loc[:,"num"] > 10]
print(out_df)

    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  Cooking   58
==================================================
46
==================================================
   groups  num
0  Movies   46
   groups  num
1  Sports    8
    groups  num
3  Fishing   12
==================================================
0    46
1     8
2    12
3    12
4     6
5    58
Name: num, dtype: int64
==================================================
0    46
1     8
2    12
3    12
4     6
5    58
Name: num, dtype: int64
==================================================
0    46
1     8
2    12
3    12
4     6
5    58
Name: num, dtype: int64
==================================================
    groups  num
0   Movies   46
2   Coding   12
3  Fishing   12
5  Cooking   58